# A conda environment with all useful package for gammasim-tools developers
name: gammasim-tools-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pyyaml
  - numpy
  - astropy
  - matplotlib-base
  - sphinx
  - pre-commit
  - pytest
  - pytest-cov
  - scipy
  - pymongo
  - numpydoc
  - sphinx
  - sphinx_rtd_theme
  - pyproj
  - zstandard
  - conda-forge::eventio>=1.5.0
  - pyflakes

# cheatsheet
# create: conda env create -f environment.yml
# activate: conda activate gammasim-tools-dev
# update: conda env update -f environment.yml --prune
