# A conda environment with all useful package for gammasim-tools developers
name: movie-reviews
channels:
  - conda-forge
dependencies:
  - python=3.10
  - requests
  - beautifulsoup4
  - pandas

# cheatsheet
# create: conda env create -f environment.yml
# activate: conda activate movie-reviews
# update: conda env update -f environment.yml --prune
